export const TRANSPORT_SYNTH_BATCH_SIZE = 2;

export const SELECTION_SYNTH_BATCH_SIZE = 8;

export const PREVIEW_SYNTH_BATCH_SIZE = 1;

export const PREVIEW_DURATION_MS = 350;

export const SYNTH_START_PREROLL_SECONDS = 0.015;

export const SELECTION_SYNTH_START_PREROLL_SECONDS = 0.12;

export const SELECTION_STREAM_STARTUP_BUFFER_SECONDS = 0.6;

export const SELECTION_STREAM_MIN_STARTUP_BATCHES = 3;
