import type { MusicToolContract } from './types';

export const MUSIC_GENERATE_TOOL_CONTRACT: MusicToolContract = {
  name: 'music.generate',
  description: 'Generate symbolic music via NotaGen backends and optionally convert to MusicXML.',
  inputSchema: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    type: 'object',
    additionalProperties: false,
    properties: {
      backend: { type: 'string', enum: ['huggingface', 'hf', 'huggingface-space', 'hf-space', 'space', 'gradio-space'] },
      hfToken: { type: 'string' },
      hf_token: { type: 'string' },
      modelId: { type: 'string' },
      model_id: { type: 'string' },
      revision: { type: 'string' },
      prompt: { type: 'string' },
      spaceId: { type: 'string' },
      space_id: { type: 'string' },
      period: { type: 'string' },
      composer: { type: 'string' },
      instrumentation: { type: 'string' },
      inputArtifactId: { type: 'string' },
      input_artifact_id: { type: 'string' },
      seedArtifactId: { type: 'string' },
      seed_artifact_id: { type: 'string' },
      dryRun: { type: 'boolean' },
      dry_run: { type: 'boolean' },
      validate: { type: 'boolean' },
      deepValidate: { type: 'boolean' },
      deep_validate: { type: 'boolean' },
      includePrompt: { type: 'boolean' },
      include_prompt: { type: 'boolean' },
      includeRawOutput: { type: 'boolean' },
      include_raw_output: { type: 'boolean' },
      includeAbc: { type: 'boolean' },
      include_abc: { type: 'boolean' },
      includeContent: { type: 'boolean' },
      include_content: { type: 'boolean' },
      timeoutMs: { type: 'number', minimum: 1 },
      timeout_ms: { type: 'number', minimum: 1 },
      maxNewTokens: { type: 'number', minimum: 1 },
      max_new_tokens: { type: 'number', minimum: 1 },
      temperature: { type: 'number', minimum: 0 },
      topP: { type: 'number', minimum: 0, maximum: 1 },
      top_p: { type: 'number', minimum: 0, maximum: 1 },
      promptSeedAbcCharLimit: { type: 'number', minimum: 1 },
      prompt_seed_abc_char_limit: { type: 'number', minimum: 1 },
      outputAbcCharLimit: { type: 'number', minimum: 1 },
      output_abc_char_limit: { type: 'number', minimum: 1 },
    },
  },
  outputSchema: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    oneOf: [
      {
        type: 'object',
        required: ['ready', 'specialist', 'backend', 'request'],
        properties: {
          ready: { type: 'boolean' },
          specialist: { type: 'string', enum: ['notagen'] },
          backend: { type: 'string' },
          request: { type: 'object' },
          generation: { anyOf: [{ type: 'object' }, { type: 'null' }] },
          message: { type: 'string' },
          outputArtifactId: { type: 'string' },
          generatedAbcArtifactId: { type: 'string' },
          validationWarnings: { type: 'object' },
          validationErrors: {
            type: 'array',
            items: { type: 'object' },
          },
          error: { type: 'string' },
        },
      },
      {
        type: 'object',
        required: ['error'],
        properties: {
          error: { type: 'string' },
        },
      },
    ],
  },
};

