import type { MusicToolContract } from './types';

export const MUSIC_CHORDGAN_TRANSFER_TOOL_CONTRACT: MusicToolContract = {
  name: 'music.chordgan_transfer',
  description: 'Prepare or execute ChordGAN transfer requests (Phase 0 dry-run scaffold).',
  inputSchema: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    type: 'object',
    additionalProperties: false,
    properties: {
      backend: { type: 'string', enum: ['huggingface-space', 'hf-space', 'space', 'gradio-space'] },
      spaceId: { type: 'string' },
      space_id: { type: 'string' },
      style: { type: 'string' },
      styleTarget: { type: 'string' },
      style_target: { type: 'string' },
      inputFormat: { type: 'string', enum: ['musicxml', 'xml', 'midi'] },
      input_format: { type: 'string', enum: ['musicxml', 'xml', 'midi'] },
      content: { type: 'string' },
      text: { type: 'string' },
      contentBase64: { type: 'string' },
      content_base64: { type: 'string' },
      inputArtifactId: { type: 'string' },
      input_artifact_id: { type: 'string' },
      includeMidi: { type: 'boolean' },
      include_midi: { type: 'boolean' },
      includeMusicXml: { type: 'boolean' },
      include_music_xml: { type: 'boolean' },
      persistArtifacts: { type: 'boolean' },
      persist_artifacts: { type: 'boolean' },
      validate: { type: 'boolean' },
      deepValidate: { type: 'boolean' },
      deep_validate: { type: 'boolean' },
      timeoutMs: { type: 'number', minimum: 1 },
      timeout_ms: { type: 'number', minimum: 1 },
      dryRun: { type: 'boolean' },
      dry_run: { type: 'boolean' },
      applyModeHint: { type: 'string', enum: ['replace', 'append'] },
      apply_mode_hint: { type: 'string', enum: ['replace', 'append'] },
    },
  },
  outputSchema: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    oneOf: [
      {
        type: 'object',
        required: ['ready', 'specialist', 'backend', 'request'],
        properties: {
          ready: { type: 'boolean' },
          specialist: { type: 'string', enum: ['chordgan'] },
          backend: { type: 'string' },
          phase: { type: 'string' },
          dryRun: { type: 'boolean' },
          request: { type: 'object' },
          capabilities: { type: 'object' },
          generation: { anyOf: [{ type: 'object' }, { type: 'null' }] },
          warnings: { type: 'array', items: { type: 'string' } },
          message: { type: 'string' },
        },
      },
      {
        type: 'object',
        required: ['ok', 'error'],
        properties: {
          ok: { type: 'boolean' },
          error: {
            type: 'object',
            required: ['code', 'message'],
            properties: {
              code: { type: 'string' },
              message: { type: 'string' },
              phase: { type: 'string' },
            },
          },
        },
      },
    ],
  },
};

