#!/usr/bin/env python3
"""
Turns the SMuFL glyphs the tool strip uses into SVG path data, so the strip's icons are plain SVG:
no font to load, every glyph fitted and centred by its real outline (a clef cannot overflow its button).

Which glyphs: every SMuFL code point (U+E000..U+F8FF) that appears, as an escape, a raw character or a 0xE... number, in the
files below. Outlines come from Leland (MuseScore's font) and fall back to Bravura for the glyphs Leland's
subset lacks. Both are SIL OFL 1.1 (webmscore-fork/fonts/*/OFL.txt).

Run:  python3 scripts/generate-glyph-paths.py   (needs fontTools; the output is committed)
"""
import re
import sys
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "webmscore-fork" / "fonts"
OUT = ROOT / "components/shell/toolbar/strip/icons/glyphPaths.generated.ts"

SOURCES = [
    ROOT / "components/toolbar",
    ROOT / "components/shell/toolbar",
]
ESCAPE = re.compile(r"\\u([Ee][0-9A-Fa-f]{3}|[Ff][0-7][0-9A-Fa-f]{2})")
NUMERIC = re.compile(r"\b0x([eE][0-9a-fA-F]{3}|[fF][0-7][0-9a-fA-F]{2})\b")
RAW = re.compile(r"[-]")


def codepoints() -> list[int]:
    found: set[int] = set()
    for root in SOURCES:
        for path in root.rglob("*"):
            if path.suffix not in (".ts", ".tsx") or path.name == OUT.name:
                continue
            text = path.read_text(encoding="utf-8")
            found.update(int(m.group(1), 16) for m in ESCAPE.finditer(text))
            found.update(ord(m.group(0)) for m in RAW.finditer(text))
            found.update(int(m.group(1), 16) for m in NUMERIC.finditer(text))
    return sorted(found)


def main() -> int:
    leland = TTFont(FONTS / "leland/Leland.otf")
    bravura = TTFont(FONTS / "bravura/Bravura.otf")
    fonts = [("leland", leland), ("bravura", bravura)]
    lines: list[str] = []
    missing: list[str] = []
    for cp in codepoints():
        for name, font in fonts:
            glyph_name = font.getBestCmap().get(cp)
            if glyph_name:
                break
        else:
            missing.append(f"U+{cp:04X}")
            continue
        upm = font["head"].unitsPerEm
        scale = 1000 / upm
        glyphs = font.getGlyphSet()
        bounds = BoundsPen(glyphs)
        glyphs[glyph_name].draw(bounds)
        if bounds.bounds is None:
            continue
        x0, y0, x1, y1 = (v * scale for v in bounds.bounds)
        pen = SVGPathPen(glyphs, ntos=lambda v: str(int(round(v))))
        # Font space is y-up with the baseline at 0; SVG is y-down, so flip and keep the baseline at y = 0.
        glyphs[glyph_name].draw(TransformPen(pen, (scale, 0, 0, -scale, 0, 0)))
        d = pen.getCommands()
        # [path, left, top, width, height] in thousandths of an em, y down from the baseline.
        lines.append(
            f"  '{cp:04X}': ['{d}', {round(x0)}, {round(-y1)}, {round(x1 - x0)}, {round(y1 - y0)}],"
        )
    OUT.write_text(
        "// Generated by scripts/generate-glyph-paths.py from Leland and Bravura (SIL OFL 1.1). Do not edit.\n"
        "/** SMuFL code point (hex) -> [SVG path, left, top, width, height], in thousandths of an em, y down from the baseline. */\n"
        "export const GLYPH_PATHS: Readonly<Record<string, readonly [string, number, number, number, number]>> = {\n"
        + "\n".join(lines)
        + "\n};\n",
        encoding="utf-8",
    )
    print(f"{len(lines)} glyphs, {OUT.stat().st_size // 1024} KB", "missing: " + " ".join(missing) if missing else "")
    return 0


if __name__ == "__main__":
    sys.exit(main())
